#!/bin/bash

source "$CONFIG_DIR/colors.sh" # Loads all defined colors

# This is a demo config to show some of the most important commands more easily.
# This is meant to be changed and configured, as it is intentionally kept sparse.
# For a more advanced configuration example see my dotfiles:
# https://github.com/FelixKratz/dotfiles

PLUGIN_DIR="$CONFIG_DIR/plugins"
ITEM_DIR="$CONFIG_DIR/items"

##### Bar Appearance #####
# Configuring the general appearance of the bar, these are only some of the
# options available. For all options see:
# https://felixkratz.github.io/SketchyBar/config/bar
# If you are looking for other colors, see the color picker:
# https://felixkratz.github.io/SketchyBar/config/tricks#color-picker

sketchybar --bar height=45        \
    blur_radius=30   \
    position=top     \
    sticky=off       \
    padding_left=10  \
    padding_right=10 \
    color=$BAR_COLOR

##### Changing Defaults #####
# We now change some default values that are applied to all further items
# For a full list of all available item properties see:
# https://felixkratz.github.io/SketchyBar/config/items

sketchybar --default \
    icon.font="SF Pro:Semibold:14.0"  \
    icon.color=$ICON_COLOR            \
    label.font="SF Pro:Medium:13.0"   \
    label.color=$WHITE                \
    background.color=$ITEM_BG_COLOR   \
    background.corner_radius=6        \
    background.height=26              \
    padding_left=4                    \
    padding_right=4                   \
    icon.padding_left=8               \
    icon.padding_right=4              \
    label.padding_left=4              \
    label.padding_right=8

# -- Left Side Items --
source $ITEM_DIR/spaces.sh

# -- Right Side Items --
source $ITEM_DIR/calendar.sh
sketchybar --add item right_gap right --set right_gap width=16 background.drawing=off icon.drawing=off label.drawing=off
source $ITEM_DIR/weather.sh
source $ITEM_DIR/vpn.sh
source $ITEM_DIR/volume.sh
source $ITEM_DIR/battery.sh
source $ITEM_DIR/cpu.sh
source $ITEM_DIR/ram.sh
source $ITEM_DIR/media.sh

##### Finalizing Setup #####
# The below command is only needed at the end of the initial configuration to
# force all scripts to run the first time, it should never be run in an item script.

# ===== STYLE: floating-pills =====
sketchybar --bar height=45 y_offset=0 margin=0 corner_radius=0 border_width=0 \
           color=0x00000000 blur_radius=0
PILL="background.drawing=on background.color=0x59000000 background.corner_radius=9 background.height=28 background.border_width=1 background.border_color=0x26ffffff"
for it in calendar weather vpn volume battery cpu ram media; do
  sketchybar --set "$it" $PILL
done
# ===== /STYLE =====

sketchybar --update
